services:
  hugo:
    container_name: supplies
    image: banderson/hugo:0.155.3
    ports:
      - 1313:1313
    volumes:
      - ./:/app
    working_dir: /app
    command: ["hugo", "--logLevel", "info", "server", "--bind", "0.0.0.0"]
